#app = ''
primary_region = 'ord'

[build]

[env]
  CUDA_LAUNCH_BLOCKING = '1'
  DB_PATH = '/data/queue5.db'
  HUGGINGFACE_HUB_CACHE = '/data/hf_cache'
  MP3_DIRECTORY = '/data/mp3_cache'
  PYANNOTE_CACHE = '/data/pyannote_cache'
  SCALE_TO_ZERO_DURATION = '180'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '10gb'

[http_service]
  internal_port = 8080

[[vm]]
  size = 'a100-40gb'
